name: 'Install cached modules'
description: 'Run pnpm install with cached modules'

runs:
    using: 'composite'
    steps:
        - uses: actions/setup-node@v4
          with:
              node-version-file: '.nvmrc'

        - name: Install pnpm
          uses: pnpm/action-setup@v3
          id: pnpm-install
          with:
              run_install: false

        - name: Get pnpm store directory
          id: pnpm-cache
          shell: bash
          run: |
              echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

        - name: Setup pnpm cache
          uses: actions/cache@v4
          with:
              path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
              key: pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
              restore-keys: |
                  pnpm-store-

        - name: Install dependencies
          shell: bash
          run: pnpm install --frozen-lockfile
